### ISSUE TITLE
User Auth / Splash page review

### ISSUE THREAD

**Issue by juliajykim** [DavidWoolner/EraBnB#3]
splash:
- [x] background image should only take 2/3 of screen and search bar should be in the top of the image under the nav bar

Auth form:
- [x] both : should have button to use demouser no matter what form you are in

sign up:
- [x] error messages pushes input area out of the container.
![Screen Shot 2021-09-09 at 5 00 22 PM](https://user-images.githubusercontent.com/59833955/132764457-04651be6-988d-4fea-91f0-697e0b76a357.png)

**Comment by DavidWoolner** [comment]
Complete!
